#set_property PACKAGE_PIN E6 [get_ports clk]
#set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property -dict {PACKAGE_PIN F16  IOSTANDARD LVCMOS33} [get_ports {LEDS[0]}]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS33} [get_ports {LEDS[1]}]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS33} [get_ports {LEDS[2]}]
set_property -dict {PACKAGE_PIN C16 IOSTANDARD LVCMOS33} [get_ports {LEDS[3]}]
set_property -dict {PACKAGE_PIN B16 IOSTANDARD LVCMOS33} [get_ports {LEDS[4]}]
set_property -dict {PACKAGE_PIN A16 IOSTANDARD LVCMOS33} [get_ports {LEDS[5]}]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS33} [get_ports {LEDS[6]}]
set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVCMOS33} [get_ports {hb_led[0]}]

set_property -dict {PACKAGE_PIN Y3  IOSTANDARD LVCMOS18} [get_ports data_in0]
set_property -dict {PACKAGE_PIN AC1 IOSTANDARD LVCMOS18} [get_ports data_in1]
set_property -dict {PACKAGE_PIN V2  IOSTANDARD LVCMOS18} [get_ports data_in2]
set_property -dict {PACKAGE_PIN V1  IOSTANDARD LVCMOS18} [get_ports data_in3]
set_property -dict {PACKAGE_PIN Y4  IOSTANDARD LVCMOS18} [get_ports odr_out]

set_property -dict {PACKAGE_PIN Y12 IOSTANDARD LVCMOS18} [get_ports {debug[0]}]
set_property -dict {PACKAGE_PIN U5 IOSTANDARD LVCMOS18} [get_ports {debug[1]}]
set_property -dict {PACKAGE_PIN AA2 IOSTANDARD LVCMOS18} [get_ports {debug[2]}]
set_property -dict {PACKAGE_PIN W5  IOSTANDARD LVCMOS18} [get_ports {debug[3]}]

set_property -dict {PACKAGE_PIN AA7  IOSTANDARD LVCMOS18} [get_ports dclk_out]
set_property -dict {PACKAGE_PIN Y2  IOSTANDARD LVCMOS18} [get_ports miso]
set_property -dict {PACKAGE_PIN AA1  IOSTANDARD LVCMOS18} [get_ports mosi]
set_property -dict {PACKAGE_PIN AB4 IOSTANDARD LVCMOS18} [get_ports spi_clk]
set_property -dict {PACKAGE_PIN AB3 IOSTANDARD LVCMOS18} [get_ports spi_cs_n]


# AD4134 GPIO control pins (UltraZed-EG FMC pinout from ADI reference)
set_property -dict {PACKAGE_PIN Y12  IOSTANDARD LVCMOS18} [get_ports ad4134_resetn]
set_property -dict {PACKAGE_PIN U5   IOSTANDARD LVCMOS18} [get_ports ad4134_pdn]
set_property -dict {PACKAGE_PIN AA2  IOSTANDARD LVCMOS18} [get_ports ad4134_mode]
set_property -dict {PACKAGE_PIN AC7  IOSTANDARD LVCMOS18} [get_ports ad4134_dclkio]
set_property -dict {PACKAGE_PIN AC2  IOSTANDARD LVCMOS18} [get_ports ad4134_pinbspi]
